dataset: data/raw.csv

preprocessing:
  scale: True
  encode: True

model:
  type: KNeighborsClassifier
  params:
    n_neighbors: 5
    weights: uniform




training:
  test_size: 0.2
  random_state: 42

target: Species    # 👈 put your actual target column here
